name: OnePlus SM8750 Build SuKiSu SUSFS
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_13'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444-lz4kd'

jobs:
  build:
    runs-on: ubuntu-latest
    # 添加写入Release的权限
    permissions:
      contents: write  # 允许修改Release
      packages: write
      actions: write
      security-events: write
      
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      # [原有步骤保持不变...]
      # 从 "Maximize build space" 到 "Upload Image" 的步骤不变

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: SuKiSu_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
         path: ./AnyKernel3/*

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image_SuKiSu_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
         path: kernel_workspace/kernel_platform/dist/Image

      # 新增Release上传步骤
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # 上传所有AnyKernel3文件和Image
          files: |
            kernel_workspace/kernel_platform/dist/AnyKernel3/*
            kernel_workspace/kernel_platform/dist/Image
          # 使用KSU版本号作为标签
          tag_name: v${{ env.KSUVER }}
          # Release名称包含构建信息
          name: "SuKiSu Kernel ${{ env.KSUVER }} (${{ github.event.inputs.FEIL }})"
          draft: false
          prerelease: true
          # 如果标签已存在则更新Release
          update: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
